import type { HairColorOption, HairstyleOption } from '@/components/salon-experience-types';

export const hairstyleOptions: HairstyleOption[] = [
  // ── Male ──────────────────────────────────────────────────────────────────
  {
    id: 'male-low-fade-crop',
    label: 'รองทรงต่ำ (Low Fade Crop)',
    category: 'male',
    description: 'ทรงผู้ชายยอดฮิตในไทย ด้านข้างไล่เฟดต่ำ ด้านบนสั้นมีเท็กซ์เจอร์',
    prompt: 'Apply a low taper fade haircut. The fade is very subtle and low, only at the very bottom of the sideburns and the nape (neckline). Keep the sides and back mostly full, dark, and thick. The top is short with soft piecey texture, styled mostly forward. The overall look should be natural, clean, and conservative, with no high shaved skin on the sides.',
    thumbnail: '/hair-styles/korean-low-taper-v2.png',
  },
  {
    id: 'male-two-block-korean',
    label: 'ทูบล็อกเกาหลี (Two Block)',
    category: 'male',
    description: 'ทรงยอดนิยมในไทย ข้างสั้น ด้านบนมีวอลุ่ม ดูเกาหลีทันสมัย',
    prompt: 'Apply a Korean two-block haircut with shorter sides and back but still some visible side bulk, not shaved to the skin. Keep the top clearly longer and fuller than the sides, with soft natural volume and a slightly tousled Korean salon finish. The shape should show a visible disconnection between the fuller top section and the neater side section. Make it look youthful, modern, and polished.',
    thumbnail: '/hair-styles/korean-two-block.png',
  },
  {
    id: 'male-comma-hair',
    label: 'คอมม่าแฮร์ (Comma Hair)',
    category: 'male',
    description: 'หน้าม้าปัดโค้งสไตล์ไอดอล ทรงนิยมในร้านไทย',
    prompt: 'Apply a comma hair haircut with a clearly visible curved front fringe as the signature feature. The fringe should sweep across the forehead and curl inward on one side like a comma shape, sitting just above one eyebrow. Keep the top softly voluminous and polished, with neat short-to-medium sides and a healthy semi-gloss Korean idol finish.',
    thumbnail: '/hair-styles/korean-comma-hair.png',
  },
  {
    id: 'male-french-crop',
    label: 'เฟรนช์ครอป (French Crop)',
    category: 'male',
    description: 'ทรงสั้นดูแลง่าย ได้ลุคสะอาดคมชัด เหมาะอากาศเมืองไทย',
    prompt: 'Apply a French crop haircut with a short compact top and a straight blunt fringe across the upper forehead as the key feature. Keep the fringe flat, sharp, and clearly horizontal, not parted or swept. The sides and back should be tighter and cleaner than the top, with a low fade or taper. The overall result should feel crisp, tidy, and structured.',
    thumbnail: '/hair-styles/korean-french-crop.png',
  },
  {
    id: 'male-undercut-slick-back',
    label: 'อันเดอร์คัตเสย (Slick Back)',
    category: 'male',
    description: 'ทรงคลาสสิกยอดนิยมในไทย เปิดหน้า ดูมืออาชีพ',
    prompt: 'Apply a slick-back undercut haircut with very short clean sides and back and a clearly longer top. Slick the top straight back away from the forehead with a smooth glossy finish, as if styled with pomade. Keep the forehead fully open and the contrast between the tight sides and sleek top strong and obvious. Do not add a shaved part line unless it appears naturally from the styling.',
    thumbnail: '/hair-styles/korean-slick-back.png',
  },
  {
    id: 'male-high-fade-buzz',
    label: 'รองทรงสูง (High Fade Buzz)',
    category: 'male',
    description: 'เฟดสูงดูหล่อคม เป็นทรงยอดฮิตในกลุ่มนักศึกษาไทย',
    prompt: 'Apply a high skin fade haircut with a short textured top. The sides and back are shaved very high up towards the crown of the head, showing a clear skin fade with high contrast between the skin and the hair. The top remains dark and short with textured volume, creating a sharp, modern, and high-impact masculine silhouette with a very clean, crisp hairline.',
    thumbnail: '/hair-styles/korean-high-fade-v2.png',
  },
  {
    id: 'male-textured-quiff',
    label: 'ควิฟเท็กซ์เจอร์ (Textured Quiff)',
    category: 'male',
    description: 'ด้านบนพองนิดหน่อย มีเท็กซ์เจอร์ ดูเท่ทันสมัย',
    prompt: 'Apply a textured quiff haircut with the front lifted above the forehead to create clear volume at the hairline. Keep the top medium length with matte piecey texture and visible separation, while the sides stay shorter and cleaner with a soft fade. The silhouette should be tallest at the front and flow naturally backward without looking stiff.',
    thumbnail: '/hair-styles/korean-textured-quiff.png',
  },
  {
    id: 'male-bowl-cut-modern',
    label: 'ทรงบาวล์โมเดิร์น (Modern Bowl)',
    category: 'male',
    description: 'ทรงบาวล์เกาหลีที่กำลังฮิตในไทย ขอบตัดเนี้ยบ ดูมินิมอล',
    prompt: 'Apply a modern Korean bowl cut with a smooth rounded dome shape on top and a precise blunt perimeter line wrapping around the head. Keep the top neat, flat, and polished, with the bowl outline clearly visible. The lower sides and back should be much shorter to create a strong contrast under the rounded top section. The result should feel minimal, clean, and fashion-forward.',
    thumbnail: '/hair-styles/korean-modern-bowl.png',
  },
  {
    id: 'male-curtain-hair',
    label: 'ม่านผมชาย (Curtain Hair)',
    category: 'male',
    description: 'ผมยาวกลางแยกกลาง สไตล์เกาหลีนิยมในไทย',
    prompt: 'Apply a men curtain hairstyle with a clean center part and longer front sections falling on both sides of the face like curtains. Let the front pieces frame the cheeks naturally, with medium length hair and soft movement. Keep the sides softer and fuller than a fade. The finish should be relaxed, natural, and Korean-inspired, with light healthy shine and no heavy product.',
    thumbnail: '/hair-styles/korean-curtain-hair.png',
  },
  {
    id: 'male-shaggy-wolf',
    label: 'แชกกี้วูล์ฟ (Shaggy Wolf)',
    category: 'male',
    description: 'ทรงวูล์ฟสำหรับผู้ชาย เลเยอร์เยอะ ดูร็อคแต่ก็สบายตา',
    prompt: 'Apply a men shaggy wolf cut with heavy visible layers, strong texture, and a fuller crown. Keep the top rounder and more voluminous, then let the hair break into wispy feathered ends around the sides and back. Add loose face-framing pieces and a slightly rebellious rock-inspired silhouette. The finish should look airy, natural, and textured rather than sleek.',
    thumbnail: '/hair-styles/korean-shaggy-wolf.png',
  },

  // ── Female ────────────────────────────────────────────────────────────────
  {
    id: 'female-hush-cut',
    label: 'ฮัชคัต (Hush Cut)',
    category: 'female',
    description: 'เลเยอร์เกาหลีทรงฮิตในไทย พลิ้วเบาและดูแพง',
    prompt: 'Apply a professional Korean Hush Cut with soft, airy, and highly textured layers. The length should fall gracefully between the chin and collarbone. Key features include delicate wispy ends that create a lightweight floating effect and soft face-framing layers that blend seamlessly. The overall look should be elegant, voluminous yet airy, with a premium salon finish and natural movement.',
    thumbnail: '/hair-styles/korean-hush-cut.png',
  },
  {
    id: 'female-wolf-cut-soft',
    label: 'วูล์ฟคัตซอฟต์ (Soft Wolf Cut)',
    category: 'female',
    description: 'ทรงฮิตมากในไทยช่วงหลัง เลเยอร์ชัดแต่ยังนุ่มหวาน',
    prompt: 'Apply a Soft Wolf Cut with distinct layered volume at the crown and soft, cascading feathered layers throughout the length. The top should be rounded and full, tapering down to wispy, textured ends around the shoulders. Include soft curtain bangs or face-framing layers that curve gently around the cheekbones. The finish must be romantic, feminine, and textured with natural-looking movement.',
    thumbnail: '/hair-styles/korean-soft-wolf.png',
  },
  {
    id: 'female-lob-c-curl',
    label: 'ล็อบปลายงุ้ม (Lob C-Curl)',
    category: 'female',
    description: 'ทรงประบ่ายอดนิยมในไทย ปลายงุ้มช่วยรับกรอบหน้า',
    prompt: 'Apply a structured Long Bob (Lob) with a precise, high-definition C-Curl at the ends. The mid-lengths should be kept sleek, glossy, and straight to maximize shine. The signature element is the ends, which should be styled with a round brush to create a smooth, deep, inward-curving bounce that cradles the chin and jawline. The hair must appear thick, healthy, and perfectly polished, embodying the sophisticated, minimalist Korean office-chic aesthetic.',
    thumbnail: '/hair-styles/korean-lob-c-curl.png',
  },
  {
    id: 'female-long-s-curl',
    label: 'เลเยอร์ยาวลอนเบา (Long S-Curl)',
    category: 'female',
    description: 'ทรงยอดนิยมในไทย ลุคหวานหรู ดูหนาผมสุขภาพดี',
    prompt: 'Apply long, voluminous hair with clearly defined, large-barrel S-Curl waves cascading down the lengths. The waves are soft, loose, and symmetrical. The hair looks bouncy, touchable, and ultra-glossy, showcasing the quintessential Korean Goddess wave aesthetic. Maintain a clear and polished salon finish.',
    thumbnail: '/hair-styles/korean-long-s-curl.png',
  },
  {
    id: 'female-curtain-bangs',
    label: 'หน้าม้ากลาง (Curtain Bangs)',
    category: 'female',
    description: 'ทรงฮิตในไทย ช่วยบาลานซ์รูปหน้าและเพิ่มความละมุน',
    prompt: 'Apply a medium-to-long hairstyle with soft curtain bangs. The bangs have a clear center part and wispily open away from the forehead, gently framing the eyes and cheekbones. The rest of the hair features soft flattering layers with a natural polished look, emphasizing feminine softness. Premium salon finish.',
    thumbnail: '/hair-styles/korean-curtain-bangs.png',
  },
  {
    id: 'female-bob-classic',
    label: 'บ็อบคลาสสิก (Classic Bob)',
    category: 'female',
    description: 'บ็อบตัดตรงเป็นทรงยืนพื้นยอดนิยมตลอดกาลในไทย',
    prompt: 'Apply a classic blunt bob hairstyle cut exactly at chin level with a perfectly straight heavy perimeter line. The shape is symmetrical, sleek, and geometric, with smooth glossy hair. No visible layers or waves. The bob perfectly frames the face on both sides, looking timeless and tailored. Premium salon finish.',
    thumbnail: '/hair-styles/korean-classic-bob.png',
  },
  {
    id: 'female-pixie-soft',
    label: 'พิกซี่นุ่ม (Soft Pixie)',
    category: 'female',
    description: 'ทรงสั้นดูเก๋ มีเท็กซ์เจอร์นุ่ม กำลังฮิตในร้านไทย',
    prompt: 'Apply a soft feminine pixie cut. The silhouette is short and close to the head but with slightly longer soft, airy texture on top. The sides and nape are neat and tapered, with a delicate soft fringe around the forehead. The look is chic, light, and feminine, completely avoiding a spiky or severe appearance. Premium salon finish.',
    thumbnail: '/hair-styles/korean-soft-pixie.png',
  },
  {
    id: 'female-fluffy-short-bob',
    label: 'บ็อบฟลัฟฟี่ (Fluffy Short Bob)',
    category: 'female',
    description: 'บ็อบสั้นพองฟู สไตล์เกาหลีนิยมในไทย ดูสดใส',
    prompt: 'Apply a fluffy short bob hairstyle with a rounded silhouette ending between the ear and jawline. The hair has soft airy volume, looking full, bouncy, and youthful around the cheeks. The outline is rounded with light movement and a fresh Korean salon finish, appearing delightfully plush. Premium salon finish.',
    thumbnail: '/hair-styles/korean-fluffy-short-bob.png',
  },
  {
    id: 'female-see-through-bangs',
    label: 'หน้าม้าซีทรู (See-Through Bangs)',
    category: 'female',
    description: 'หน้าม้าบางเบา โปร่งแสง กำลังฮิตในไทย',
    prompt: 'Apply a beautiful medium length hairstyle featuring see-through bangs. The bangs are very thin and wispy, lightly covering the forehead while still letting the skin show through. The fringe is soft, airy, and delicate with slight center separation. The rest of the hair is smooth and feminine. Premium salon finish.',
    thumbnail: '/hair-styles/korean-see-through-bangs.png',
  },
  {
    id: 'female-bun-messy',
    label: 'มวยสูงเก๋ (Messy Top Knot)',
    category: 'female',
    description: 'มวยสูงดูเป็นธรรมชาติ สไตล์ฮิตในไทย เหมาะทุกโอกาส',
    prompt: 'Apply a messy high bun hairstyle with the hair gathered at the top of the head into a loose, relaxed top knot. The bun looks intentionally effortless, with soft flyaway pieces and wispy face-framing strands around the temples and cheeks. The impression is casual, chic, and naturally pretty. Premium salon finish.',
    thumbnail: '/hair-styles/korean-messy-bun.png',
  },
];

export const hairColorOptions: HairColorOption[] = [
  // ── Natural & Dark ─────────────────────────────────────────────────────────
  {
    id: 'natural-black',
    label: 'Natural Black',
    category: 'Natural & Dark',
    swatch: '#1a1414',
    prompt: 'Recolor the hair to natural black with soft realistic shine.',
  },
  {
    id: 'dark-brown',
    label: 'Chocolate Brown',
    category: 'Natural & Dark',
    swatch: '#4a3528',
    prompt: 'Recolor the hair to dark chocolate brown with natural depth.',
  },
  {
    id: 'deep-plum',
    label: 'Deep Plum Brown',
    category: 'Natural & Dark',
    swatch: '#3b2f3e',
    prompt: 'Recolor the hair to deep plum brown with subtle violet undertones.',
  },

  // ── Fashion & Ash ──────────────────────────────────────────────────────────
  {
    id: 'ash-brown',
    label: 'Ash Brown',
    category: 'Fashion & Ash',
    swatch: '#6a5a4f',
    prompt: 'Recolor the hair to ash brown with cool muted tone.',
  },
  {
    id: 'smoky-gray',
    label: 'Smoky Ash Gray',
    category: 'Fashion & Ash',
    swatch: '#7a7c82',
    prompt: 'Recolor the hair to smoky gray with balanced cool undertone.',
  },
  {
    id: 'lavender-ash',
    label: 'Lavender Ash',
    category: 'Fashion & Ash',
    swatch: '#8a859e',
    prompt: 'Recolor the hair to lavender ash with soft purple-gray reflect.',
  },
  {
    id: 'platinum-blonde',
    label: 'Platinum Blonde',
    category: 'Fashion & Ash',
    swatch: '#d8d2c1',
    prompt: 'Recolor the hair to platinum blonde with clean cool reflect.',
  },

  // ── Warm & Beige ───────────────────────────────────────────────────────────
  {
    id: 'milk-tea-brown',
    label: 'Milk Tea Beige',
    category: 'Warm & Beige',
    swatch: '#9a7b5f',
    prompt: 'Recolor the hair to milk tea brown with soft warm-beige reflect.',
  },
  {
    id: 'caramel-brown',
    label: 'Caramel Brown',
    category: 'Warm & Beige',
    swatch: '#a86f3b',
    prompt: 'Recolor the hair to caramel brown with warm glossy highlights.',
  },
  {
    id: 'rose-gold-beige',
    label: 'Rose Gold Beige',
    category: 'Warm & Beige',
    swatch: '#c2928b',
    prompt: 'Recolor the hair to rose gold beige with warm pinkish reflect.',
  },
  {
    id: 'copper-brown',
    label: 'Copper Brown',
    category: 'Warm & Beige',
    swatch: '#8b4a3a',
    prompt: 'Recolor the hair to copper brown with vibrant warm reflect.',
  },
];
